### ISSUE TITLE
使用snackBar出现编译错误

### ISSUE THREAD

**Issue by FerretAngel** [varletjs/varlet#1450]
# Bug report 🐞
![image](https://github.com/varletjs/varlet/assets/58507654/97e58f92-ee72-4cda-9f4a-6c7862067be3)
注释掉引用之后就能正常编译
![image](https://github.com/varletjs/varlet/assets/58507654/532c1079-ee16-4116-8d28-eeccb93e51b2)
之前使用还是正常的，后来写着写着就突然页面无法响应，发现了这个编译错误。所以我不能保证是100%触发。
之前有用js调用显示，需要引入一个css文件。但是现在我删除了，仍然有这个问题
## Version & Environment
```json
  "devDependencies": {
    "@iconify/vue": "^4.1.1",
    "less": "^4.2.0",
    "nuxt": "^3.9.0",
    "unplugin-auto-import": "^0.17.4",
    "unplugin-vue-components": "^0.26.0",
    "vue": "^3.4.5",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "@varlet/ui": "^2.22.0",
    "md-editor-v3": "^4.11.0"
  }
```
## Actual results (or Errors)
``` bash
X [ERROR] Two output files share the same path but have different contents: node_modules\.cache\vite\client\deps_temp_d1d25f80\@varlet_ui_es_Snackbar_style_index.js


 ERROR  error while updating dependencies:                                                                                                                         09:30:29  
Error: Build failed with 1 error:
error: Two output files share the same path but have different contents: node_modules\.cache\vite\client\deps_temp_d1d25f80\@varlet_ui_es_Snackbar_style_index.js
    at failureErrorWithLog (D:\projects\blog-nuxt\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1651:15)
    at D:\projects\blog-nuxt\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1059:25
    at D:\projects\blog-nuxt\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by chouchouji** [comment]
晚会会看下这个问题

**Comment by RSS1102** [comment]
看到你在使用`nuxt`，你可以参考 https://github.com/varletjs/varlet-nuxt，从而在 `nuxt` 内使用`varlet`

**Comment by FerretAngel** [comment]
![image](https://github.com/varletjs/varlet/assets/58507654/694234df-b80e-4dfa-8c17-3c8aca7a42ef)
今天我删除了手动引入的样式文件后就好了。
这个问题再也没有复现过。可能是我在哪个记不清的地方引入了样式文件，然后又使用了组件造成的吧
谢谢各位了。
